### ISSUE TITLE
Button not local unblocks person when come into lobby where is he local blocked

### ISSUE THREAD

**Issue by Mororo101** [yamiM0NSTER/DreamVR#2]
https://youtu.be/HV-sPPVhAxo

**Comment by yamiM0NSTER** [comment]
Are you still encountering that bug after recent updates? If so do you know a reliable way to reproduce it?

**Comment by Mororo101** [comment]
Yes, local block person, after that restart game and come in same instance with him, unblock him and he not appear
Edit:After unblock he appears, but need wait for that a few seconds to be appeared

**Comment by yamiM0NSTER** [comment]
So... can it be considered fixed, or nah? I don't really have influence on some of vrchat internals. So delays with functionalities like this one could happen @_@.

**Comment by Mororo101** [comment]
I think fixed, that unblocks anyway
