### ISSUE TITLE
Hand panel is enabled on desktop

### ISSUE THREAD

**Issue by Xiaolinshowdown** [yamiM0NSTER/DreamVR#9]
When I use the teleport hotkey from Notorious, it enables the Hand Panel while I am clearly in desktop. The panel appears at the bottom of the recording btw.

https://user-images.githubusercontent.com/73922086/103729394-31d9a280-4f95-11eb-94ff-c6fae428c0e4.mp4

**Comment by yamiM0NSTER** [comment]
I keep forgetting about it. It's a leftover after testing. Will be removed in next update.

**Comment by yamiM0NSTER** [comment]
Keybind was removed in one of recent updates.
